name: Build and Deploy

on:
  push:
    branches: master

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.3.0'
      
      - name: Install Project Dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Build
        run: npm run build --legacy-peer-deps
      
      - name: Verify build
        run: ls -la public